// <auto-generated />
using System;
using LeagueSquadApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LeagueSquadApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251105071042_SetDefaultForDateTimeOffsetPropsThroughModelBuilder")]
    partial class SetDefaultForDateTimeOffsetPropsThroughModelBuilder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LeagueSquadApi.Data.Models.Match", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("match_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool?>("HasTimeline")
                        .HasColumnType("boolean")
                        .HasColumnName("has_timeline");

                    b.Property<string>("Patch")
                        .HasColumnType("text")
                        .HasColumnName("patch");

                    b.Property<int?>("Queue")
                        .HasColumnType("integer")
                        .HasColumnName("queue");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.HasKey("Id");

                    b.ToTable("match");
                });

            modelBuilder.Entity("LeagueSquadApi.Data.Models.MatchTimeline", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("match_id");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at");

                    b.Property<int?>("FrameIntervalMs")
                        .HasColumnType("integer")
                        .HasColumnName("frame_interval_ms");

                    b.Property<string>("TimelineJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("timeline_json");

                    b.HasKey("Id");

                    b.ToTable("match_timeline");
                });

            modelBuilder.Entity("LeagueSquadApi.Data.Models.Participant", b =>
                {
                    b.Property<string>("MatchId")
                        .HasColumnType("text")
                        .HasColumnName("match_id");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("integer")
                        .HasColumnName("participant_id");

                    b.Property<int>("Assists")
                        .HasColumnType("integer")
                        .HasColumnName("assists");

                    b.Property<int?>("ChampionId")
                        .HasColumnType("integer")
                        .HasColumnName("champion_id");

                    b.Property<int>("Deaths")
                        .HasColumnType("integer")
                        .HasColumnName("deaths");

                    b.Property<int>("Kills")
                        .HasColumnType("integer")
                        .HasColumnName("kills");

                    b.Property<string>("Puuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("puuid");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.Property<string>("TeamPosition")
                        .HasColumnType("text")
                        .HasColumnName("team_position");

                    b.HasKey("MatchId", "ParticipantId");

                    b.HasIndex("MatchId", "Puuid")
                        .IsUnique();

                    b.ToTable("participant");
                });

            modelBuilder.Entity("LeagueSquadApi.Data.Models.Player", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("puuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("game_name");

                    b.Property<string>("Platform")
                        .HasColumnType("text")
                        .HasColumnName("platform");

                    b.Property<string>("Region")
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<string>("TagLine")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tag_line");

                    b.HasKey("Id");

                    b.ToTable("player");
                });

            modelBuilder.Entity("LeagueSquadApi.Data.Models.Squad", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("squad_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("squad");
                });

            modelBuilder.Entity("LeagueSquadApi.Data.Models.SquadMatch", b =>
                {
                    b.Property<long>("SquadId")
                        .HasColumnType("bigint")
                        .HasColumnName("squad_id");

                    b.Property<string>("MatchId")
                        .HasColumnType("text")
                        .HasColumnName("match_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ReasonForAddition")
                        .HasColumnType("text")
                        .HasColumnName("reason_for_addition");

                    b.HasKey("SquadId", "MatchId");

                    b.ToTable("sqaud_match");
                });

            modelBuilder.Entity("LeagueSquadApi.Data.Models.SquadMember", b =>
                {
                    b.Property<long>("SquadId")
                        .HasColumnType("bigint")
                        .HasColumnName("squad_id");

                    b.Property<string>("Puuid")
                        .HasColumnType("text")
                        .HasColumnName("puuid");

                    b.Property<string>("Alias")
                        .HasColumnType("text")
                        .HasColumnName("alias");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("added_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Role")
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("SquadId", "Puuid");

                    b.ToTable("squad_member");
                });
#pragma warning restore 612, 618
        }
    }
}
