// <auto-generated />
using System;
using LeagueSquadApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LeagueSquadApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LeagueSquadApi.Data.Models.Match", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("match_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<DateTimeOffset>("GameEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("game_end");

                    b.Property<DateTimeOffset>("GameStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("game_start");

                    b.Property<string>("GameType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("game_type");

                    b.Property<int>("MapId")
                        .HasColumnType("integer")
                        .HasColumnName("map_id");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mode");

                    b.Property<int>("QueueId")
                        .HasColumnType("integer")
                        .HasColumnName("queue_id");

                    b.HasKey("Id");

                    b.ToTable("match");
                });

            modelBuilder.Entity("LeagueSquadApi.Data.Models.MatchTimeline", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("match_id");

                    b.Property<string>("TimelineJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("timeline_json")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.HasKey("Id");

                    b.ToTable("match_timeline");
                });

            modelBuilder.Entity("LeagueSquadApi.Data.Models.Participant", b =>
                {
                    b.Property<string>("MatchId")
                        .HasColumnType("text")
                        .HasColumnName("match_id");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("integer")
                        .HasColumnName("participant_id");

                    b.Property<int>("Assists")
                        .HasColumnType("integer")
                        .HasColumnName("assists");

                    b.Property<int?>("ChampionId")
                        .HasColumnType("integer")
                        .HasColumnName("champion_id");

                    b.Property<int>("Deaths")
                        .HasColumnType("integer")
                        .HasColumnName("deaths");

                    b.Property<int>("Kills")
                        .HasColumnType("integer")
                        .HasColumnName("kills");

                    b.Property<string>("ParticipantsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("participants_json")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("Puuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("puuid");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.Property<string>("TeamPosition")
                        .HasColumnType("text")
                        .HasColumnName("team_position");

                    b.Property<bool>("Win")
                        .HasColumnType("boolean")
                        .HasColumnName("win");

                    b.HasKey("MatchId", "ParticipantId");

                    b.HasIndex("MatchId", "Puuid")
                        .IsUnique();

                    b.ToTable("participant");
                });

            modelBuilder.Entity("LeagueSquadApi.Data.Models.Player", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("puuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("game_name");

                    b.Property<string>("Region")
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<string>("TagLine")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tag_line");

                    b.HasKey("Id");

                    b.ToTable("player");
                });

            modelBuilder.Entity("LeagueSquadApi.Data.Models.Squad", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("squad_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("SquadMatchCount")
                        .HasColumnType("integer")
                        .HasColumnName("squad_match_count");

                    b.HasKey("Id");

                    b.ToTable("squad");
                });

            modelBuilder.Entity("LeagueSquadApi.Data.Models.SquadMatch", b =>
                {
                    b.Property<long>("SquadId")
                        .HasColumnType("bigint")
                        .HasColumnName("squad_id");

                    b.Property<string>("MatchId")
                        .HasColumnType("text")
                        .HasColumnName("match_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ReasonForAddition")
                        .HasColumnType("text")
                        .HasColumnName("reason_for_addition");

                    b.HasKey("SquadId", "MatchId");

                    b.ToTable("squad_match");
                });

            modelBuilder.Entity("LeagueSquadApi.Data.Models.SquadMember", b =>
                {
                    b.Property<long>("SquadId")
                        .HasColumnType("bigint")
                        .HasColumnName("squad_id");

                    b.Property<string>("Puuid")
                        .HasColumnType("text")
                        .HasColumnName("puuid");

                    b.Property<string>("Alias")
                        .HasColumnType("text")
                        .HasColumnName("alias");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("added_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Role")
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("SquadId", "Puuid");

                    b.ToTable("squad_member");
                });
#pragma warning restore 612, 618
        }
    }
}
